version: '3.8'

services:
  banck:
    image: pamendeza/banck-api-bpm:latest
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    restart: always
    depends_on:
      - db

  db:
      image: mongo:latest
      hostname: db
      ports:
        - "27017:27017"
      volumes:
        - /home/ubuntu/data/db:/data/db
